
class LanguagePreview {
  /// 语言名称映射
  static final getExtNameMapping = {
    '1c': '1C',
    'abnf': 'ABNF',
    'accesslog': 'Access Log',
    'actionscript': 'ActionScript',
    'ada': 'Ada',
    'angelscript': 'AngelScript',
    'apache': 'Apache',
    'applescript': 'AppleScript',
    'arcade': 'Arcade',
    'arduino': 'Arduino',
    'armasm': 'ARM Assembly',
    'asciidoc': 'AsciiDoc',
    'aspectj': 'AspectJ',
    'autohotkey': 'AutoHotkey',
    'autoit': 'AutoIt',
    'avrasm': 'AVR Assembly',
    'awk': 'AWK',
    'axapta': 'Axapta',
    'bash': 'Bash',
    'basic': 'BASIC',
    'bnf': 'BNF',
    'brainfuck': 'Brainfuck',
    'cal': 'Cal',
    'capnproto': 'Cap\'n Proto',
    'ceylon': 'Ceylon',
    'clean': 'Clean',
    'clojure-repl': 'Clojure REPL',
    'clojure': 'Clojure',
    'cmake': 'CMake',
    'coffeescript': 'CoffeeScript',
    'coq': 'Coq',
    'cos': 'Cos',
    'cpp': 'C++',
    'crmsh': 'crmsh',
    'crystal': 'Crystal',
    'c': 'C',
    'cs': 'C#',
    'csp': 'CSP',
    'css': 'CSS',
    'd': 'D',
    'dart': 'Dart',
    'delphi': 'Delphi',
    'diff': 'Diff',
    'django': 'Django',
    'dns': 'DNS',
    'dockerfile': 'Dockerfile',
    'dos': 'DOS',
    'dsconfig': 'DSConfig',
    'dts': 'TypeScript',
    'dust': 'Dust',
    'ebnf': 'EBNF',
    'elixir': 'Elixir',
    'elm': 'Elm',
    'erb': 'ERB',
    'erlang-repl': 'Erlang REPL',
    'erlang': 'Erlang',
    'excel': 'Excel',
    'fix': 'Fix',
    'flix': 'Flix',
    'fortran': 'Fortran',
    'fsharp': 'F#',
    'gams': 'GAMS',
    'gauss': 'GAUSS',
    'gcode': 'G-code',
    'gherkin': 'Gherkin',
    'glsl': 'GLSL',
    'gml': 'GML',
    'go': 'Go',
    'golo': 'Golo',
    'gradle': 'Gradle',
    'groovy': 'Groovy',
    'haml': 'HAML',
    'handlebars': 'Handlebars',
    'haskell': 'Haskell',
    'haxe': 'Haxe',
    'hsp': 'HSP',
    'htmlbars': 'HTMLBars',
    'http': 'HTTP',
    'hy': 'Hy',
    'inform7': 'Inform 7',
    'ini': 'INI',
    'irpf90': 'IRPF90',
    'isbl': 'ISBL',
    'java': 'Java',
    'javascript': 'JavaScript',
    'jboss-cli': 'JBoss CLI',
    'json': 'JSON',
    'julia-repl': 'Julia REPL',
    'julia': 'Julia',
    'kotlin': 'Kotlin',
    'lasso': 'Lasso',
    'ldif': 'LDIF',
    'leaf': 'Leaf',
    'less': 'Less',
    'lisp': 'Lisp',
    'livecodeserver': 'LiveCode Server',
    'livescript': 'LiveScript',
    'llvm': 'LLVM IR',
    'lsl': 'LSL',
    'lua': 'Lua',
    'makefile': 'Makefile',
    'markdown': 'Markdown',
    'mathematica': 'Mathematica',
    'matlab': 'MATLAB',
    'maxima': 'Maxima',
    'mel': 'MEL',
    'mercury': 'Mercury',
    'mipsasm': 'MIPS Assembly',
    'mizar': 'Mizar',
    'mojolicious': 'Mojolicious',
    'monkey': 'Monkey',
    'moonscript': 'MoonScript',
    'n1ql': 'N1QL',
    'nginx': 'Nginx',
    'nimrod': 'Nimrod',
    'nix': 'Nix',
    'nsis': 'NSIS',
    'objectivec': 'Objective-C',
    'ocaml': 'OCaml',
    'openscad': 'OpenSCAD',
    'oxygene': 'Oxygene',
    'parser3': 'Parser3',
    'perl': 'Perl',
    'pf': 'PF',
    'pgsql': 'PostgreSQL',
    'php': 'PHP',
    'plaintext': 'Plain Text',
    'pony': 'Pony',
    'powershell': 'PowerShell',
    'processing': 'Processing',
    'profile': 'Profile',
    'prolog': 'Prolog',
    'properties': 'Properties',
    'protobuf': 'Protocol Buffers',
    'puppet': 'Puppet',
    'purebasic': 'PureBASIC',
    'python': 'Python',
    'q': 'Q',
    'qml': 'QML',
    'r': 'R',
    'reasonml': 'ReasonML',
    'rib': 'RenderMan RIB',
    'roboconf': 'Roboconf',
    'routeros': 'RouterOS',
    'rsl': 'RSL',
    'ruby': 'Ruby',
    'ruleslanguage': 'Rules Language',
    'rust': 'Rust',
    'sas': 'SAS',
    'scala': 'Scala',
    'scheme': 'Scheme',
    'scilab': 'Scilab',
    'scss': 'SCSS',
    'shell': 'Shell',
    'smali': 'Smali',
    'smalltalk': 'Smalltalk',
    'sml': 'SML',
    'sqf': 'SQF',
    'sql': 'SQL',
    'stan': 'Stan',
    'stata': 'Stata',
    'step21': 'STEP 21',
    'stylus': 'Stylus',
    'subunit': 'SubUnit',
    'swift': 'Swift',
    'taggerscript': 'TaggerScript',
    'tap': 'TAP',
    'tcl': 'Tcl',
    'tex': 'TeX',
    'thrift': 'Thrift',
    'tp': 'TP',
    'twig': 'Twig',
    'typescript': 'TypeScript',
    'vala': 'Vala',
    'vbnet': 'VB.NET',
    'vbscript-html': 'VBScript HTML',
    'vbscript': 'VBScript',
    'verilog': 'Verilog',
    'vhdl': 'VHDL',
    'vim': 'Vim',
    'x86asm': 'x86 Assembly',
    'xl': 'XL',
    'xml': 'XML',
    'xquery': 'XQuery',
    'yaml': 'YAML',
    'zephir': 'Zephir',
    'vue': 'Vue',
    'graphql': 'GraphQL',
    'gn': 'Gn',
    'solidity': 'Solidity',
    'txt': 'Plain Text',
    'log': 'Log',
    'cfg': 'Config',
    'conf': 'Config',
    'csv': 'CSV',
    'h': 'C/C++ Header',
    'hpp': 'C++ Header',
    'cc': 'C++',
    'cxx': 'C++',
    'js': 'JavaScript',
    'jsx': 'JavaScript JSX',
    'ts': 'TypeScript',
    'tsx': 'TypeScript JSX',
    'py': 'Python',
    'rs': 'Rust',
    'rb': 'Ruby',
    'kt': 'Kotlin',
    'kts': 'Kotlin Script',
    'html': 'HTML',
    'htm': 'HTML',
    'yml': 'YAML',
    'sh': 'Bash',
    'zsh': 'Zsh',
    'crt': 'Plain Text',
    'pem': 'Plain Text',
  };
} 